{{- if not .Values.splunkservice.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "splunk-sli-provider.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "splunk-sli-provider.labels" . | nindent 4 }}
type: Opaque
data:
SP_HOST: {{ required "A valid SP_HOST is required to connect to the Splunk API" .Values.splunkservice.spHost | b64enc | quote }}
SP_PORT: {{ required "A valid SP_PORT is required to connect to the Splunk API" .Values.splunkservice.spPort | b64enc | quote }}
SP_USERNAME: {{ required "A valid SP_USERNAME is required to connect to the Splunk API" .Values.splunkservice.spUser | b64enc | quote }}
SP_PASSWORD: {{ required "A valid SP_PASSWORD is required to connect to the Splunk API" .Values.splunkservice.spPassword | b64enc | quote }}
SP_API_TOKEN: {{ required "A valid SP_API_TOKEN is required to connect to the Splunk API" .Values.splunkservice.spApitoken | b64enc | quote }}
SP_SESSION_KEY: {{ required "A valid SP_SESSION_KEY is required to connect to the Splunk API" .Values.splunkservice.spSessionKey | b64enc | quote }}
{{- end -}}