{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-sli-provider.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "splunk-sli-provider.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

#  Create the role of reading secrets in keptn namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-splunk-read-secret
  namespace: {{ .Release.Namespace | default .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-{{ .Release.Namespace }}-secret-read-splunk
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "splunk-sli-provider.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-splunk-read-secret
subjects:
  - kind: ServiceAccount
    name: {{ include "splunk-sli-provider.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | default .Values.namespace }}
{{- end }}